/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/health": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              status: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/{collection}": {
    get: {
      parameters: {
        path: {
          collection: string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": any;
          };
        };
      };
    };
  };
}
