import { Router } from 'express'
import fs from 'fs'
import path from 'path'
import { z } from 'zod'

const router: Router = Router()

const FieldSchema = z.object({
  name: z.string(),
  type: z.string(),
  label: z.string().optional(),
  required: z.boolean().optional(),
  unique: z.boolean().optional(),
  defaultValue: z.any().optional(),
  description: z.string().optional(),
  options: z.array(z.object({ label: z.string(), value: z.string() })).optional(),
  relationTo: z.string().optional(),
  hasMany: z.boolean().optional(),
}).passthrough()

const BlockPayloadSchema = z.object({
  type: z.string(),
  title: z.string(),
  description: z.string().optional(),
  category: z.string().optional().default('General'),
  iconName: z.string().optional().default('Box'),
  fields: z.array(FieldSchema)
})

router.post('/generate', async (req, res) => {
  try {
    const data = BlockPayloadSchema.parse(req.body)
    
    // Format the TypeScript code
    const blocksDir = path.resolve(process.cwd(), 'config/blocks')
    
    if (!fs.existsSync(blocksDir)) {
      fs.mkdirSync(blocksDir, { recursive: true })
    }

    const fileName = `${data.type}.ts`
    const filePath = path.join(blocksDir, fileName)

    const fieldsCode = data.fields.map(f => {
      let props = `    name: '${f.name}',\n    type: '${f.type}',`
      if (f.label) props += `\n    label: '${f.label}',`
      if (f.required) props += `\n    required: true,`
      if (f.unique) props += `\n    unique: true,`
      if (f.defaultValue !== undefined) {
        props += `\n    defaultValue: ${typeof f.defaultValue === 'string' ? `'${f.defaultValue}'` : JSON.stringify(f.defaultValue)},`
      }
      if (f.description) props += `\n    description: '${f.description.replace(/'/g, "\\'")}',`
      if (f.relationTo) props += `\n    relationTo: '${f.relationTo}',`
      if (f.hasMany) props += `\n    hasMany: true,`
      if (f.options?.length) {
        props += `\n    options: ${JSON.stringify(f.options)},`
      }
      return `  {\n${props}\n  },`
    }).join('\n')

    // Construct the TypeScript content
    const fileContent = `import type { BlockDefinition } from '@zenithcms/types'
// This file is auto-generated by the Zenith CMS Component Builder.
// You can freely edit this file. The GUI will sync with these changes.

export const ${data.type.replace(/-/g, '_')}: BlockDefinition = {
  type: '${data.type}',
  iconName: '${data.iconName}',
  title: '${data.title}',
  description: '${data.description || ''}',
  category: '${data.category}',
  fields: [
${fieldsCode}
  ],
  defaultContent: {}
}
`

    fs.writeFileSync(filePath, fileContent, 'utf-8')

    res.status(200).json({ success: true, message: `Block ${data.type} generated successfully`, path: filePath })
  } catch (err: any) {
    console.error('Error generating block:', err)
    res.status(400).json({ error: { message: err.message || 'Validation failed' } })
  }
})

router.get('/', (req, res) => {
  try {
    const blocksDir = path.resolve(process.cwd(), 'config/blocks')
    if (!fs.existsSync(blocksDir)) {
      return res.json({ data: [] })
    }

    const files = fs.readdirSync(blocksDir).filter(f => f.endsWith('.ts'))
    const blocks = []

    for (const file of files) {
      // Very naive extraction just to list them in the UI without compiling TS at runtime.
      // In a real scenario we'd use ts-morph or require hook.
      // Since they just need to be listed in the sidebar, returning basic info is fine.
      const content = fs.readFileSync(path.join(blocksDir, file), 'utf-8')
      const typeMatch = content.match(/type:\s*'([^']+)'/)
      const titleMatch = content.match(/title:\s*'([^']+)'/)
      const categoryMatch = content.match(/category:\s*'([^']+)'/)
      
      if (typeMatch) {
        blocks.push({
          type: typeMatch[1],
          title: titleMatch?.[1] || typeMatch[1],
          category: categoryMatch?.[1] || 'General',
          filename: file
        })
      }
    }

    res.json({ data: blocks })
  } catch (err: any) {
    console.error('Error listing blocks:', err)
    res.status(500).json({ error: { message: 'Failed to list blocks' } })
  }
})

export default router
