import * as fs from 'fs'
import * as path from 'path'

/**
 * ZenithSynthesizer — Extension Code Generator
 * ─────────────────────────────────────────────
 * Generates runtime integration hooks for collection extensions
 * (stripe-sync, seo-analyzer, etc.).
 *
 * SECURITY CONTRACT:
 * User-controlled values (options.plan, options.*) are NEVER interpolated
 * into generated TypeScript source. All user input is written to a separate
 * `.json` config file which the static hook template reads at runtime.
 * This eliminates the injection-via-codegen attack surface.
 */
export class ZenithSynthesizer {
  constructor(private outputDir: string) {}

  public synthesize(collections: any[]): void {
    for (const col of collections) {
      if (!col.extensions) continue

      for (const ext of col.extensions) {
        if (ext.type === 'stripe-sync' || ext.type === 'payment-sync') {
          this.generatePaymentHook(col.slug, ext.options || {})
        }
        if (ext.type === 'seo-analyzer') {
          this.generateSEOHook(col.slug, ext.options || {})
        }
      }
    }
  }

  /**
   * Stripe-sync extension.
   *
   * Architecture: user options go into a JSON config file only. The
   * generated .ts file is a static, non-parameterised template that
   * imports the JSON config at runtime — it contains no user-supplied
   * strings whatsoever.
   */
  private generatePaymentHook(slug: string, options: any) {
    const dir = path.join(this.outputDir, 'extensions')
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })

    const configPath = path.join(dir, `${slug}-payment-config.json`)
    fs.writeFileSync(configPath, JSON.stringify(options, null, 2))

    // Generic payment processing hook that triggers the EventHub
    const generatedPath = path.join(dir, `${slug}-payment.generated.ts`)
    const generatedContent = `// [Auto-Generated by Zenith Synthesizer]
import { env } from '../../../src/config/env'
import paymentConfig from './${slug}-payment-config.json'
import { eventHub } from '../../../src/services/event-hub'

export async function processPayment(data: any) {
  try {
    const payload = {
      ...data,
      metadata: { source: 'zenith-cms-sync', plan: paymentConfig.plan },
      response: { url: undefined, sessionId: undefined, error: undefined }
    }
    
    await eventHub.emit('payment:checkout:create', payload)
    
    if (payload.response.error) {
      console.warn('[Zenith Payment Hook] Payment provider returned an error:', payload.response.error)
      return { id: 'error_payment_id' }
    }
    
    return { id: payload.response.sessionId || 'mock_payment_id' }
  } catch (err: any) {
    console.warn('[Zenith Payment Hook] Failed to dispatch payment event:', err.message)
    return { id: 'error_payment_id' }
  }
}
`
    fs.writeFileSync(generatedPath, generatedContent)

    // Append to user-editable hook registry
    const userHookPath = path.join(dir, 'index.ts')
    if (fs.existsSync(userHookPath)) {
      let userContent = fs.readFileSync(userHookPath, 'utf8')
      if (!userContent.includes(`processPayment`)) {
        userContent = `import { processPayment } from '../.zenith/extensions/${slug}-payment.generated'\n` + userContent
        const hookTemplate = `
export const ${slug}PaymentSync = async (data: any) => {
  try {
    const payment = await processPayment(data)
    data.paymentId = payment.id
  } catch (err: any) {
    console.error('[Zenith Hook Override] Payment processing failed:', err.message)
  }
  return data
}
`
        fs.writeFileSync(userHookPath, userContent + hookTemplate)
      }
    }
  }

  /**
   * SEO-Analyzer extension.
   * No user input enters the generated source — safe by design.
   */
  private generateSEOHook(slug: string, _options: any) {
    const dir = this.outputDir
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })

    const generatedContent = `/** AUTO-GENERATED BY ZENITH COMPILER - DO NOT EDIT **/

export function calculateSEOScore(text: string): number {
  if (!text) return 0
  let score = 50
  if (text.length > 50) score += 20
  if (text.length > 100) score += 10
  if (text.toLowerCase().includes('zenith') || text.toLowerCase().includes('cms')) score += 20
  return Math.min(score, 100)
}
`
    const generatedPath = path.join(dir, `${slug}-seo.generated.ts`)
    fs.writeFileSync(generatedPath, generatedContent, 'utf-8')
  }
}

