import * as fs from 'fs'
import * as path from 'path'

export class ZenithSynthesizer {
  constructor(private outputDir: string) {}

  public synthesize(collections: any[]): void {
    for (const col of collections) {
      if (!col.extensions) continue

      for (const ext of col.extensions) {
        if (ext.type === 'stripe-sync') {
          this.generateStripeHook(col.slug, ext.options || {})
        }
        if (ext.type === 'seo-analyzer') {
          this.generateSEOHook(col.slug, ext.options || {})
        }
      }
    }
  }

  private generateStripeHook(slug: string, options: any) {
    const generatedContent = `/** AUTO-GENERATED BY ZENITH COMPILER - DO NOT EDIT **/
import Stripe from 'stripe'
import { env } from '../config/env';


export const baseStripeConfig = {
  secretKey: env.STRIPE_SECRET_KEY || '',
  plan: '${options.plan || 'basic'}'
}

export async function createStripeCustomer(email: string) {
  if (!baseStripeConfig.secretKey) {
    console.warn('[Zenith stripe-sync] Stripe secret key missing. Skipping customer creation.')
    return { id: 'mock_stripe_cust_id' }
  }
  const stripe = new Stripe(baseStripeConfig.secretKey, { apiVersion: '2023-10-16' as any })
  return await stripe.customers.create({
    email,
    metadata: { source: 'zenith-cms-sync', plan: baseStripeConfig.plan }
  })
}
`
    const generatedPath = path.join(this.outputDir, `${slug}-stripe.generated.ts`)
    const dir = path.dirname(generatedPath)
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true })
    }
    fs.writeFileSync(generatedPath, generatedContent, 'utf-8')

    // Generate companion user file only if it doesn't exist (protecting developer customizations)
    const userPath = path.join(this.outputDir, `../../hooks/${slug}-beforeChange.ts`)
    if (!fs.existsSync(userPath)) {
      const userContent = `import { createStripeCustomer } from '../.zenith/extensions/${slug}-stripe.generated'

export default async function beforeChangeHook(data: any) {
  if (data.email) {
    try {
      const customer = await createStripeCustomer(data.email)
      data.stripeCustomerId = customer.id
    } catch (err: any) {
      console.error('[Zenith Hook Override] Stripe customer creation failed:', err.message)
    }
  }
  return data;
}
`
      const userDir = path.dirname(userPath)
      if (!fs.existsSync(userDir)) {
        fs.mkdirSync(userDir, { recursive: true })
      }
      fs.writeFileSync(userPath, userContent, 'utf-8')
    }
  }

  private generateSEOHook(slug: string, options: any) {
    const generatedContent = `/** AUTO-GENERATED BY ZENITH COMPILER - DO NOT EDIT **/

export function calculateSEOScore(text: string) {
  if (!text) return 0
  let score = 50
  if (text.length > 50) score += 20
  if (text.length > 100) score += 10
  if (text.includes('zenith') || text.includes('cms')) score += 20
  return Math.min(score, 100)
}
`
    const generatedPath = path.join(this.outputDir, `${slug}-seo.generated.ts`)
    const dir = path.dirname(generatedPath)
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true })
    }
    fs.writeFileSync(generatedPath, generatedContent, 'utf-8')
  }
}
