apiVersion: v1
kind: Service
metadata:
  name: zenith-core
  namespace: zenith
spec:
  selector:
    app: zenith-core
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: zenith-admin
  namespace: zenith
spec:
  selector:
    app: zenith-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
