import * as fs from 'fs'
import * as path from 'path'
import { generatePostgresCode } from './generators/postgres'
import { generateMongoCode } from './generators/mongodb'

export interface CompilationManifest {
  collections: {
    slug: string;
    fields: any[];
    database: 'postgres' | 'mongodb';
  }[];
}

export class ZenithCompiler {
  constructor(private config: any, private outputPath: string) {}

  public async compile(): Promise<void> {
    const manifest = this.buildManifest(this.config)
    
    let generatedCode = `/** AUTO-GENERATED BY ZENITH COMPILER - DO NOT EDIT **/ \n\n`
    
    // Add runtime imports
    generatedCode += `import mongoose from 'mongoose'\n`
    generatedCode += `import { eq, and } from 'drizzle-orm'\n\n`

    for (const col of manifest.collections) {
      if (col.database === 'postgres') {
        generatedCode += generatePostgresCode(col)
      } else {
        generatedCode += generateMongoCode(col)
      }
    }

    const outputDir = path.dirname(this.outputPath)
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true })
    }

    const existingContent = fs.existsSync(this.outputPath) ? fs.readFileSync(this.outputPath, 'utf-8') : ''
    if (existingContent !== generatedCode) {
      fs.writeFileSync(this.outputPath, generatedCode, 'utf-8')
    }
  }

  private buildManifest(config: any): CompilationManifest {
    const dbType = config.database?.type === 'postgres' ? 'postgres' : 'mongodb'
    return {
      collections: (config.collections || []).map((col: any) => ({
        slug: col.slug,
        fields: col.fields || [],
        database: dbType,
      })),
    }
  }
}
