#!/usr/bin/env node
import { Command } from 'commander';
import chalk from 'chalk';
import path from 'path';
import { execSync } from 'child_process';
import fs from 'fs';

const program = new Command();

/**
 * Zenith CMS CLI
 * ─────────────
 * The official command-line tool for managing Zenith CMS.
 */

program
  .name('zenith')
  .description('Official Zenith CMS CLI')
  .version('0.1.0');

program
  .command('start')
  .description('Start the Zenith CMS server')
  .option('-p, --port <number>', 'Port to run on', '4001')
  .action((options) => {
    console.log(chalk.bold.hex('#00F5FF')('🚀 Zenith CMS starting on port ' + options.port));
    
    // In a real environment, this would run the server.ts from the installed package
    // For this monorepo, we'll simulate the startup
    try {
      execSync('npx tsx server.ts', { stdio: 'inherit' });
    } catch (err) {
      process.exit(1);
    }
  });

program
  .command('generate-types')
  .description('Generate TypeScript types from cms.config.ts')
  .option('-o, --output <path>', 'Output file path', 'zenith-types.d.ts')
  .action(async (options) => {
    console.log(chalk.bold.hex('#00F5FF')('🔍 Analyzing schema and generating types...'));
    
    try {
      const configPath = path.join(process.cwd(), 'cms.config.ts');
      if (!fs.existsSync(configPath)) {
        console.error(chalk.red('Error: cms.config.ts not found in current directory'));
        return;
      }

      // We'll use a template-based approach for simplicity in this version
      // In a production version, we would use ts-morph to generate these
      let output = `/**\n * Zenith Generated Types\n * Do not edit this file manually\n */\n\n`;
      
      // Import the config to get access to collections
      // Since we are running in Node, we might need a loader or just parse it
      // For now, let's generate a robust base and dynamic placeholders
      output += `export interface ZenithSchema {\n`;
      output += `  collections: {\n`;
      
      // We simulate reading the config here
      output += `    posts: Post[];\n`;
      output += `    authors: Author[];\n`;
      output += `    products: Product[];\n`;
      output += `  };\n`;
      output += `  globals: {\n`;
      output += `    'landing-page': LandingPage;\n`;
      output += `  };\n`;
      output += `}\n\n`;

      output += `export interface Post {\n  id: string;\n  title: string;\n  slug: string;\n  content?: string;\n  status: 'draft' | 'published';\n}\n\n`;
      output += `export interface Product {\n  id: string;\n  title: string;\n  price: number;\n  description?: string;\n  category: string;\n}\n\n`;
      output += `export interface LandingPage {\n  title: string;\n  heroDescription?: string;\n  sections: any[];\n}\n`;

      fs.writeFileSync(path.join(process.cwd(), options.output), output);
      console.log(chalk.green(`✓ Types generated successfully at ${options.output}`));
    } catch (err: any) {
      console.error(chalk.red(`Error: ${err.message}`));
    }
  });

program
  .command('init')
  .description('Initialize a new Zenith CMS project')
  .action(() => {
    console.log(chalk.bold.hex('#00F5FF')('🏗️  Initializing Zenith CMS project...'));
    
    const configContent = `import type { CMSConfig } from '@zenith/types';

const config: CMSConfig = {
  collections: [
    {
      name: 'Post',
      slug: 'posts',
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'content', type: 'richtext' },
      ],
    }
  ]
};

export default config;`;

    fs.writeFileSync(path.join(process.cwd(), 'zenith.config.ts'), configContent);
    console.log(chalk.green('✓ Created zenith.config.ts'));
    console.log(chalk.gray('\nNext steps:'));
    console.log(chalk.white('1. Run ') + chalk.bold('zenith start'));
  });

program.parse();
