import type { BlockDefinition } from '@zenith-open/zenithcms-types'

// This file is auto-generated by the Zenith CMS Component Builder.
// You can freely edit this file. The GUI will sync with these changes.

export const hero: BlockDefinition = {
  slug: 'hero',
  labels: { singular: 'hero', plural: 'heros' },
  fields: [
    {
      type: 'text',
      name: 'headline',
      label: 'headline',
    },
    {
      type: 'text',
      name: 'subheadline',
      label: 'subheadline',
    },
    {
      type: 'text',
      name: 'callToAction',
      label: 'callToAction',
    },
    {
      type: 'media',
      name: 'backgroundImage',
      label: 'backgroundImage',
    },
    {
      type: 'text',
      name: 'anchorId',
      label: 'Anchor ID',
    },
    {
      type: 'select',
      name: 'theme',
      label: 'Theme',
      options: [{"label":"Default","value":"default"},{"label":"Light","value":"light"},{"label":"Dark","value":"dark"},{"label":"Cyber-Purple Gradient","value":"cyber-emerald"},{"label":"Glassmorphic Translucent","value":"glassmorphic"}],
    },
    {
      type: 'select',
      name: 'paddingY',
      label: 'Vertical Padding',
      options: [{"label":"None","value":"none"},{"label":"Small","value":"small"},{"label":"Medium","value":"medium"},{"label":"Large","value":"large"}],
    },
    {
      type: 'select',
      name: 'containerWidth',
      label: 'Container Width',
      options: [{"label":"Boxed","value":"boxed"},{"label":"Full Width","value":"full-width"}],
    }
  ],
  admin: { 
    category: 'General', 
    icon: 'Box',
    description: 'Generated Component'
  }
}
