import createClient from 'openapi-fetch'
import type { paths } from './api-types' // Generated by openapi-typescript

// Fallback to localhost if environment variable is not defined
const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:4000'

// Create typesafe client instance
export const client = createClient<paths>({ baseUrl: API_URL })
